-- The launch catalogue is versioned in:
--   migrations/202607270003_seed_verified_universities.sql
--
-- Keep this file empty so `supabase db reset` does not apply a second,
-- dashboard-only copy of the seed after the migration chain.
