import type { Extraction, ProfilePayload } from './types.js'

type Config = { supabaseUrl: string; anonKey: string }
type Session = { access_token: string; user: { email?: string } }
type University = { id: string; name: string }
let session: Session | null = null
let extraction: Extraction | null = null
let universities: University[] = []
const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T
const status = (message: string, kind = '') => { $('status').textContent = message; $('status').className = kind }
async function config(): Promise<Config> { const saved=await chrome.storage.local.get(['supabaseUrl','anonKey']); return {supabaseUrl:typeof saved.supabaseUrl==='string'?saved.supabaseUrl:'',anonKey:typeof saved.anonKey==='string'?saved.anonKey:''} }
function configPanel(value: Config): void { $('config').innerHTML=`<details><summary>Connection settings</summary><label>Supabase URL<input id="url" value="${value.supabaseUrl}" placeholder="https://project.supabase.co"></label><label>Public anon key<input id="key" value="${value.anonKey}" type="password"></label><button id="settings" type="button">Save settings</button></details>`; $('settings').onclick=async()=>{await chrome.storage.local.set({supabaseUrl:$<HTMLInputElement>('url').value.trim(),anonKey:$<HTMLInputElement>('key').value.trim()});status('Settings saved.','ok')} }
function authPanel(): void { $('auth').innerHTML=session?`<p class="ok">Signed in as ${session.user.email ?? 'admin'}</p>`:`<fieldset><legend>Admin sign in</legend><label>Email<input id="email" type="email"></label><label>Password<input id="password" type="password"></label><button id="login" type="button">Sign in</button></fieldset>`; if(!session)$('login').onclick=login }
async function login(): Promise<void> { const c=await config(); const email=$<HTMLInputElement>('email').value,password=$<HTMLInputElement>('password').value; const response=await fetch(`${c.supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:c.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})}); const result=await response.json() as Session & {error_description?:string}; if(!response.ok||!result.access_token){status(result.error_description??'Sign-in failed.','error');return} session=result;authPanel();status('Signed in.','ok') }
function reviewPanel(): void { if(!extraction)return; $('review').innerHTML=`<fieldset><legend>Review found data</legend><label>University<input id="universityQuery" placeholder="Search the public university list"></label><select id="university"><option value="">Choose the matching university</option></select><label>Reviewed payload JSON<textarea id="payload"></textarea></label><p class="muted">Absent: ${extraction.absent.join(', ')||'none'}<br>Needs review (excluded): ${extraction.needsReview.join(', ')||'none'}</p></fieldset>`; const payload=$<HTMLTextAreaElement>('payload');payload.value=JSON.stringify(extraction.found,null,2);const render=(query='')=>{$<HTMLSelectElement>('university').innerHTML='<option value="">Choose the matching university</option>'+universities.filter(u=>`${u.name} ${u.id}`.toLowerCase().includes(query.toLowerCase())).slice(0,100).map(u=>`<option value="${u.id}">${u.name} (${u.id})</option>`).join('')};render();$('universityQuery').oninput=()=>render($<HTMLInputElement>('universityQuery').value); $('save').innerHTML='<button id="saveButton" type="button">Save to database</button>'; $('saveButton').onclick=save }
async function read(): Promise<void> { const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab.id){status('No active tab.','error');return} const result=await chrome.tabs.sendMessage(tab.id,{type:'extract'}) as Extraction; extraction=result; const c=await config(); const response=await fetch(`${c.supabaseUrl}/rest/v1/universities?select=id,name&order=name`,{headers:{apikey:c.anonKey,Authorization:`Bearer ${c.anonKey}`}});if(!response.ok){status('Could not load the public university list. Check settings.','error');return} universities=await response.json() as University[];reviewPanel();status('Page read. Review every value before saving.','ok') }
async function save(): Promise<void> { if(!session){status('Sign in before saving.','error');return} const id=$<HTMLSelectElement>('university').value;if(!id){status('Choose the matching university first.','error');return} let reviewed:ProfilePayload;try{reviewed=JSON.parse($<HTMLTextAreaElement>('payload').value) as ProfilePayload}catch{status('Reviewed JSON is invalid.','error');return} const c=await config();const response=await fetch(`${c.supabaseUrl}/functions/v1/admin-api`,{method:'POST',headers:{apikey:c.anonKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'ingest_university_profile',payload:{...reviewed,universityId:id}})});const result=await response.json() as {error?:string;counts?:unknown;absent?:unknown};status(response.ok?`Saved. ${JSON.stringify({counts:result.counts,absent:result.absent})}`:result.error??'Save failed.',response.ok?'ok':'error') }
async function initialise(): Promise<void> { configPanel(await config());authPanel();$('read').onclick=read }
void initialise()
