create type public.source_verification as enum ('unverified_sample', 'verified');

create table public.sources (
  id text primary key,
  origin text not null,
  url text,
  retrieved_at date not null,
  verification public.source_verification not null default 'unverified_sample'
);

create table public.universities (
  id text primary key,
  name text not null,
  city text not null,
  country text not null,
  flag text not null,
  tagline text not null,
  description text not null,
  photo_seed text not null,
  highlights text[] not null default '{}',
  source_id text not null references public.sources(id)
);

create type public.university_fact_kind as enum (
  'tuition',
  'living_cost',
  'application_fee',
  'deadline',
  'scholarship',
  'language',
  'intake'
);

create table public.university_facts (
  university_id text not null references public.universities(id) on delete cascade,
  kind public.university_fact_kind not null,
  value text,
  numeric_value numeric,
  currency text,
  source_id text references public.sources(id),
  unknown_reason text,
  suggested_action text,
  primary key (university_id, kind),
  constraint university_fact_known_or_unknown check (
    (value is not null and source_id is not null and unknown_reason is null and suggested_action is null)
    or
    (value is null and source_id is null and unknown_reason is not null and suggested_action is not null)
  )
);

create table public.programs (
  id text primary key,
  university_id text not null references public.universities(id) on delete cascade,
  name text not null,
  degree text not null,
  field text not null,
  source_id text not null references public.sources(id)
);

create type public.program_fact_kind as enum ('duration', 'tuition');

create table public.program_facts (
  program_id text not null references public.programs(id) on delete cascade,
  kind public.program_fact_kind not null,
  value text,
  numeric_value numeric,
  currency text,
  source_id text references public.sources(id),
  unknown_reason text,
  suggested_action text,
  primary key (program_id, kind),
  constraint program_fact_known_or_unknown check (
    (value is not null and source_id is not null and unknown_reason is null and suggested_action is null)
    or
    (value is null and source_id is null and unknown_reason is not null and suggested_action is not null)
  )
);

create type public.requirement_kind as enum ('ielts');

create table public.requirements (
  id bigint generated by default as identity primary key,
  university_id text not null references public.universities(id) on delete cascade,
  kind public.requirement_kind not null,
  value text,
  numeric_value numeric,
  source_id text references public.sources(id),
  unknown_reason text,
  suggested_action text,
  unique (university_id, kind),
  constraint requirement_known_or_unknown check (
    (value is not null and source_id is not null and unknown_reason is null and suggested_action is null)
    or
    (value is null and source_id is null and unknown_reason is not null and suggested_action is not null)
  )
);

create table public.scholarships (
  id text primary key,
  name text not null,
  amount_value text,
  amount_numeric numeric,
  currency text,
  amount_source_id text references public.sources(id),
  amount_unknown_reason text,
  amount_suggested_action text,
  source_id text not null references public.sources(id),
  constraint scholarship_amount_known_or_unknown check (
    (amount_value is not null and amount_source_id is not null and amount_unknown_reason is null and amount_suggested_action is null)
    or
    (amount_value is null and amount_source_id is null and amount_unknown_reason is not null and amount_suggested_action is not null)
  )
);

create table public.university_scholarships (
  university_id text not null references public.universities(id) on delete cascade,
  scholarship_id text not null references public.scholarships(id) on delete cascade,
  primary key (university_id, scholarship_id)
);

alter table public.sources enable row level security;
alter table public.universities enable row level security;
alter table public.university_facts enable row level security;
alter table public.programs enable row level security;
alter table public.program_facts enable row level security;
alter table public.requirements enable row level security;
alter table public.scholarships enable row level security;
alter table public.university_scholarships enable row level security;

create policy "read sources" on public.sources for select to anon, authenticated using (true);
create policy "read universities" on public.universities for select to anon, authenticated using (true);
create policy "read university facts" on public.university_facts for select to anon, authenticated using (true);
create policy "read programs" on public.programs for select to anon, authenticated using (true);
create policy "read program facts" on public.program_facts for select to anon, authenticated using (true);
create policy "read requirements" on public.requirements for select to anon, authenticated using (true);
create policy "read scholarships" on public.scholarships for select to anon, authenticated using (true);
create policy "read university scholarships" on public.university_scholarships for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on all tables in schema public to anon, authenticated;

-- This is the future public-only boundary. The app currently reads the base tables so
-- unverified sample rows remain visible. Switching the repository to this view exposes
-- only university rows whose owning source has been verified.
create view public.verified_universities
with (security_invoker = true)
as
select u.*
from public.universities u
join public.sources s on s.id = u.source_id
where s.verification = 'verified';

grant select on public.verified_universities to anon, authenticated;

comment on table public.university_facts is
  'Known facts require source_id; unknown facts require a reason and suggested action.';
comment on view public.verified_universities is
  'Stable public-read boundary for the later verified-only launch mode.';
