begin;

-- Generic, sourced profile data. These labels deliberately contain no provider
-- name: a future QS import is only one possible verified source.
create type public.program_degree_level as enum ('bachelor', 'master', 'mba', 'phd');
create type public.program_subject_area as enum (
  'Arts and Humanities', 'Business and Management', 'Engineering and Technology',
  'Life Sciences and Medicine', 'Natural Sciences', 'Social Sciences and Management'
);

alter table public.programs
  add column degree_level public.program_degree_level,
  add column subject_area public.program_subject_area;

update public.programs
set degree_level = case
  when lower(degree) ~ '(master|m\.s\.|m\.a\.|msc|meng)' then 'master'::public.program_degree_level
  when lower(degree) ~ '(mba|master of business)' then 'mba'::public.program_degree_level
  when lower(degree) ~ '(ph\.d|doctor)' then 'phd'::public.program_degree_level
  else 'bachelor'::public.program_degree_level
end,
subject_area = case
  when field ilike '%business%' or field ilike '%management%' then 'Business and Management'::public.program_subject_area
  when field ilike '%humanit%' or field ilike '%art%' then 'Arts and Humanities'::public.program_subject_area
  when field ilike '%life science%' or field ilike '%medicine%' then 'Life Sciences and Medicine'::public.program_subject_area
  when field ilike '%natural science%' then 'Natural Sciences'::public.program_subject_area
  when field ilike '%social science%' then 'Social Sciences and Management'::public.program_subject_area
  else 'Engineering and Technology'::public.program_subject_area
end;

alter table public.programs
  alter column degree_level set not null,
  alter column subject_area set not null;

alter type public.university_fact_kind add value if not exists 'international_student_pct';
alter type public.university_fact_kind add value if not exists 'living_accommodation';
alter type public.university_fact_kind add value if not exists 'living_food';
alter type public.university_fact_kind add value if not exists 'living_transport';
alter type public.university_fact_kind add value if not exists 'living_utilities';
alter type public.university_fact_kind add value if not exists 'employability_rate';
alter type public.university_fact_kind add value if not exists 'employability_summary';
alter type public.university_fact_kind add value if not exists 'faculty_count';

create table public.rankings (
  id bigint generated by default as identity primary key,
  university_id text not null references public.universities(id) on delete cascade,
  label text not null,
  rank_display text not null,
  year integer,
  source_id text not null references public.sources(id)
);

create table public.campuses (
  id bigint generated by default as identity primary key,
  university_id text not null references public.universities(id) on delete cascade,
  name text not null,
  city text not null,
  country text not null,
  source_id text not null references public.sources(id)
);

create index rankings_university_id_idx on public.rankings (university_id);
create index rankings_source_id_idx on public.rankings (source_id);
create index campuses_university_id_idx on public.campuses (university_id);
create index campuses_source_id_idx on public.campuses (source_id);

alter table public.rankings enable row level security;
alter table public.campuses enable row level security;
create policy "read rankings" on public.rankings for select to anon, authenticated using (true);
create policy "read campuses" on public.campuses for select to anon, authenticated using (true);
grant select on public.rankings, public.campuses to anon, authenticated;

comment on column public.programs.degree_level is 'Normalized sourced programme level; retain degree for the published label.';
comment on column public.programs.subject_area is 'Normalized sourced subject bucket for programme exploration.';
comment on table public.rankings is 'Repeating sourced ranking records; rank_display preserves published notation.';
comment on table public.campuses is 'Repeating sourced campus locations.';

-- Reusable programme-import pattern. Insert one verified source row first, then
-- insert only programme names and facts transcribed from that exact URL. Keep
-- source_id non-null for every programme and fact. Do not add a count or a
-- programme name until it appears on the retrieved official catalogue page.
--
-- No batch is inserted here because this task did not include the promised
-- single university catalogue URL. Leaving this migration data-free is safer
-- than inventing a programme or claiming a source was retrieved.
--
-- insert into public.sources (id, name, url, retrieved_at, verification) values
--   ('example-catalogue-2026', 'University — official catalogue', 'https://…', current_date, 'verified');
-- insert into public.programs (id, university_id, name, degree, field, degree_level, subject_area, source_id) values
--   ('example-program-id', 'university-id', 'Published programme name', 'Published degree label', 'Published field', 'bachelor', 'Engineering and Technology', 'example-catalogue-2026');
-- insert into public.program_facts (program_id, kind, value, numeric_value, currency, amount_period, source_id, unknown_reason, suggested_action) values
--   ('example-program-id', 'duration', 'Published duration', null, null, null, 'example-catalogue-2026', null, null),
--   ('example-program-id', 'tuition', null, null, null, null, null, 'The official catalogue page does not publish programme tuition.', 'Check the university fee page.');

commit;
